config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  get 'admin', to: 'admin#index'
  get 'sessions/destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :theatres
  resources :movies
  resources :shows, only: [:new, :create, :index, :show]
  resources :bookings, only: [:new, :create, :index]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :show

  after_commit :enqueue_post_booking_job, :update_seats_left
  AVAILABLE_SEATS_CACHE = Rails.application.config.cache_config[:SHOWS_AVAILABLE]

  private
  def enqueue_post_booking_job
    PostBookingJob.perform_later(self.id)
  end

  def update_seats_left
    thisBooking = Booking.find(self.id)
    puts "update number of seats ", self.id, thisBooking.show.id, self.seats
    $redis.decrby("#{AVAILABLE_SEATS_CACHE}_#{thisBooking.show.id}", self.seats)

  end


end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :language, presence: true
  validates :release_date, presence: true

  has_many :shows, dependent: :delete_all


end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :movie
  belongs_to :theatre
  has_many :bookings, dependent: :delete_all
  delegate :seats, to: :bookings

  validates :slot, presence: true, inclusion: { in: [1, 2, 3, 4] }
  validates :date, presence: true
  validates :current_available_bookings, presence: true, numericality: { greater_than_or_equal_to: 0 }

  # Uniqueness constraint: same movie, theatre, slot, date combination
  validates :slot, uniqueness: { scope: [:theatre_id, :date], message: "already allocated for this date in this theatre" }

  before_validation :set_default_bookings, on: :create
  after_create :initialize_redis_seat_count
  private
  AVAILABLE_SEATS_CACHE = Rails.application.config.cache_config[:SHOWS_AVAILABLE]
  def set_default_bookings
    if self.current_available_bookings.nil? && theatre.present?
      self.current_available_bookings = theatre.capacity
    end
  end

  def initialize_redis_seat_count
    puts "Add to redis ", current_available_bookings
    # $redis.set("show_available_seats#{id}": current_available_bookings)
    $redis.set("#{AVAILABLE_SEATS_CACHE}_#{id}", current_available_bookings)
  end
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :city, presence: true
  validates :capacity, presence: true

  has_many :shows, dependent: :delete_all

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: URI::MailTo::EMAIL_REGEXP }
  has_many :bookings, dependent: :delete_all
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  include AccessConcern
  before_action :require_admin, only: [:index, :new, :create, :edit, :update, :destroy]
  def index
  end
end

app/controllers/bookings_controller.rb
require 'pagy/extras/bootstrap'  # for Bootstrap pagination UI
class BookingsController < ApplicationController
  include AccessConcern
  include Pagy::Backend
  before_action :require_login_alias
  
  CACHE_EXPIRY = Rails.application.config.cache_config[:cache_expiry]
  SHOWS_AVAILABLE = Rails.application.config.cache_config[:SHOWS_AVAILABLE]
  def new
    @movies = fetchAllMovies
    @theatres = fetchAllTheatres

    @selected_movie = params[:movie_id].present? ? Movie.find_by(id: params[:movie_id]) : nil
    @selected_theatre = params[:theatre_id].present? ? Theatre.find_by(id: params[:theatre_id]) : nil

    if @selected_movie
      @shows = Show.includes(:theatre).where(movie: @selected_movie).order(date: :desc, slot: :asc)
    elsif @selected_theatre
      @shows = Show.includes(:movie).where(theatre: @selected_theatre).order(date: :desc, slot: :asc)
    else
      @shows = []
    end
  end

  def create
    show = Show.find(params[:show_id])
    seats_to_book = params[:seats].to_i

    if seats_to_book <= 0
      redirect_back fallback_location: new_booking_path, alert: "Number of seats must be at least 1"
      return
    end

    if seats_to_book > show.current_available_bookings
      redirect_back fallback_location: new_booking_path, alert: "Cannot book more than #{show.current_available_bookings} seats"
      return
    end

    # Create booking
    Rails.logger.info "Current user: #{current_user.inspect}"
    Rails.logger.info "Show: #{show.inspect}"
    Rails.logger.info "Seats to book: #{seats_to_book}"

    booking = Booking.create!(
      user: current_user,
      show: show,
      seats: seats_to_book
    )

    # Reduce available seats
    show.update!(current_available_bookings: show.current_available_bookings - seats_to_book)
    redirect_to bookings_path, notice: "Booking confirmed for #{seats_to_book} seats"
  end

  def index
    Rails.logger.info "Pagy items param: 5"
    @pagy, @bookings = pagy(
      current_user.bookings.includes(show: [:movie, :theatre])
      .order('shows.date ASC')
      .references(:show),
      items: 5
    )
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include AccessConcern
  before_action :require_admin, only: [:index, :new, :create, :show, :destroy]
  CACHE_EXPIRY = Rails.application.config.cache_config[:cache_expiry]
  MOVIES_LIST_CACHE = Rails.application.config.cache_config[:MOVIES_LIST]


  def index
    puts MOVIES_LIST_CACHE, CACHE_EXPIRY
    @movies = fetchAllMovies
    # @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      invalidate_cache(MOVIES_LIST_CACHE)
      redirect_to movies_path, notice: "Movie created successfully"
    else
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    invalidate_cache(MOVIES_LIST_CACHE)
    redirect_to movies_path, notice: "Movie deleted successfully"
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :language, :release_date)
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  include AccessConcern
  before_action :require_admin

  def new
    @show = Show.new
    @movies = fetchAllMovies
    # @movies = Movie.all
    @theatres = fetchAllTheatres
    # @theatres = Theatre.all
  end

  def create
    @show = Show.new(show_params)
    if @show.save
        redirect_to shows_path, notice: "Show created successfully"
    else
      @movies = Movie.all
      @theatres = Theatre.all
      render :new
    end
  end

  def index
    @shows = Show.all.order(date: :asc)
  end

  def show
    puts "here..."
    @show = Show.find(params[:id])
    puts "show ->", @show.bookings
  end

  private


  def show_params
    params.require(:show).permit(:slot, :date, :movie_id, :theatre_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # render json: UserBlueprint.render(users)
  end

  def show
  	puts User.find(params[:id]).name
    @user = User.find(params[:id])
    render json: UserBlueprint.render(@user, view: :normal)
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    
    if @user.save
      redirect_to @user, notice: 'User was successfully created.' # Redirect on success
    else
      # Re-render the form if validation fails
      render :new, status: :unprocessable_entity 
    end
  end

  private
  # This method was missing or misspelled. It enforces Strong Parameters.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
require 'pagy/extras/bootstrap'

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/theatre_helper.rb
module TheatreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="container my-5">
    
  <h1 class="mb-5 text-center">Admin Dashboard</h1>
  
  </div>
  <div class="row g-4">
    <div class="col-md-4">
      <%= link_to theatres_path, class: "card text-center text-decoration-none text-dark h-100" do %>
        <div class="card-body d-flex flex-column justify-content-center align-items-center">
          <h4 class="card-title">Theatres</h4>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <%= link_to movies_path, class: "card text-center text-decoration-none text-dark h-100" do %>
        <div class="card-body d-flex flex-column justify-content-center align-items-center">
          <h4 class="card-title">Movies</h4>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <%= link_to shows_path, class: "card text-center text-decoration-none text-dark h-100" do %>
        <div class="card-body d-flex flex-column justify-content-center align-items-center">
          <h4 class="card-title">Shows</h4>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CineBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% unless request.path == root_path %>

      <div class="card-footer d-flex justify-content-end">
      <%= link_to 'Logout', logout_path, method: :delete, class: "btn btn-secondary" %>
    </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show " role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close p-4" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

    <%= yield %>
  </body>
</html>